# Parses a stock list text file and outputs JSON
if ARGV.length != 2
  puts "ERROR: You must provide a filename for parsing and a filename to write json to"
  exit
end

file = File.open(ARGV[1], "w")

file.print "// This file was generated by parse.rb\ntestStockDataArray = ["

need_comma = false

tickers = []
names = []

File.open(ARGV[0], "r").each do |line|
  l = line.split(/\t/)
  if l.length >= 2
    if need_comma
      file.puts ","
    else
      file.puts
      need_comma = true
    end
    ticker,name = l[0..1]
    tickers << ticker
    names << name
    file.print "  { ticker: \"" + ticker + "\", name: \"" + name + "\" }"
  end
end

file.puts
file.puts "];"
file.puts
file.print "testStockDataMap = {"

need_comma = false
for i in 0...tickers.length
  if need_comma
    file.puts ","
  else
    file.puts
    need_comma = true
  end
  file.print "  \"" + tickers[i] + "\": testStockDataArray[" + i.to_s + "]"
end

file.puts
file.puts "};"